apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: backend-pod-failure
  namespace: staging
spec:
  action: pod-failure
  mode: one
  selector:
    labelSelectors:
      app.kubernetes.io/name: mini-idp-backend
  duration: '30s'
  scheduler:
    cron: '@every 2m'
