apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockRootContainers
metadata:
  name: block-root-containers
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - argocd
