{{- if not .Values.secrets.externalSecretsEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mini-idp-backend.fullname" . }}-db-credentials
  labels:
    {{- include "mini-idp-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
{{- end }}
