{{- if .Values.secrets.externalSecretsEnabled -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.secretStoreName }}
  labels:
    {{- include "mini-idp-backend.labels" . | nindent 4 }}
spec:
  provider:
    {{- if eq .Values.secrets.secretStoreProvider "vault" }}
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "mini-idp-backend-role"
          serviceAccountRef:
            name: {{ include "mini-idp-backend.serviceAccountName" . }}
    {{- else if eq .Values.secrets.secretStoreProvider "aws" }}
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | default "us-east-1" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "mini-idp-backend.serviceAccountName" . }}
    {{- end }}
{{- end }}
