{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mini-idp-backend.fullname" . }}
  labels:
    {{- include "mini-idp-backend.labels" . | nindent 4 }}
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "mini-idp-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
